version: "3"
services:
  gp20a051_cuda-11-4:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - ENV_VAR=value
    env_file:
      - proxy.env
    volumes:
      - ./ET-BERT:/ET-BERT
    command: /bin/bash
    tty: true
    stop_signal: SIGINT
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]